"""Confluence config generator — pure functions producing valid config dicts.

Takes SpaceInfo list from v2 discovery + user selections, returns a dict
that passes ConfluenceConfig.from_dict() validation. No side effects.

RAISE-1059 (S1051.6)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from raise_cli.adapters.confluence_config import ArtifactRouting
from raise_cli.adapters.confluence_discovery import PageNode
from raise_cli.adapters.models.docs import SpaceInfo

# Default routing for common artifact types when none provided
_DEFAULT_ROUTING: dict[str, ArtifactRouting] = {
    "adr": ArtifactRouting(parent_title="Architecture", labels=["adr", "architecture"]),
    "developer": ArtifactRouting(
        parent_title="Developer Docs", labels=["developer-docs"]
    ),
}


def generate_confluence_config(
    spaces: list[SpaceInfo],
    selected_space: str,
    instance_url: str,
    instance_name: str = "default",
    routing: dict[str, ArtifactRouting] | None = None,
) -> dict[str, Any]:
    """Generate a Confluence config dict from discovery data.

    Args:
        spaces: Discovered spaces from ConfluenceDiscoveryService.discover_spaces().
        selected_space: Space key chosen by the user.
        instance_url: Confluence base URL (e.g. "https://x.atlassian.net/wiki").
        instance_name: Logical instance identifier (defaults to "default").
        routing: Optional artifact routing overrides. Defaults provided if None.

    Returns:
        Dict matching ConfluenceConfig multi-instance format.

    Raises:
        ValueError: If selected_space is not in the spaces list.
    """
    space_keys = {s.key for s in spaces}
    if selected_space not in space_keys:
        available = ", ".join(sorted(space_keys))
        msg = f"Space '{selected_space}' not found. Available: {available}"
        raise ValueError(msg)

    effective_routing = routing if routing is not None else _DEFAULT_ROUTING

    routing_dict: dict[str, dict[str, Any]] = {
        name: {
            "parent_title": r.parent_title,
            "labels": r.labels,
        }
        for name, r in effective_routing.items()
    }

    return {
        "default_instance": instance_name,
        "instances": {
            instance_name: {
                "url": instance_url,
                "space_key": selected_space,
                "instance_name": instance_name,
                "routing": routing_dict,
            },
        },
    }


# ── Routing suggestion from page tree ────────────────────────────────

# Artifact type → keywords that match top-level page titles (case-insensitive substring)
_ROUTING_KEYWORDS: dict[str, list[str]] = {
    "adr": ["architecture decision", "adr"],
    "roadmap": ["roadmap"],
    "developer": ["developer doc", "developer guide"],
    "retrospective": ["retrospective", "retro"],
}


def suggest_routing(tree: PageNode) -> dict[str, ArtifactRouting]:
    """Suggest artifact routing from top-level page titles.

    Matches each top-level child title against known artifact type keywords
    using case-insensitive substring matching. Returns a dict of artifact
    type → ArtifactRouting for each match found.

    Args:
        tree: Root PageNode whose children are top-level pages.

    Returns:
        Dict of artifact_type → ArtifactRouting for matched pages.
    """
    suggestions: dict[str, ArtifactRouting] = {}
    for child in tree.children:
        title_lower = child.title.lower()
        for artifact_type, keywords in _ROUTING_KEYWORDS.items():
            if artifact_type in suggestions:
                continue  # already matched this type
            for keyword in keywords:
                if keyword in title_lower:
                    suggestions[artifact_type] = ArtifactRouting(
                        parent_title=child.title,
                        labels=[artifact_type],
                    )
                    break
    return suggestions


# ── YAML writer ──────────────────────────────────────────────────────

_CONFIG_HEADER = """\
# Confluence adapter configuration — generated by /rai-adapter-setup
# See: https://raise.dev/docs/adapters/confluence
#
# default_instance: which instance to use when none specified
# instances.<name>.url: Confluence base URL
# instances.<name>.space_key: target space
# instances.<name>.routing: artifact type → parent page + labels
#
"""


def write_confluence_config(
    config_dict: dict[str, Any],
    project_root: Path,
    overwrite: bool = False,
) -> Path:
    """Write a config dict to .raise/confluence.yaml.

    Args:
        config_dict: Config dict (should pass ConfluenceConfig.from_dict()).
        project_root: Project root directory.
        overwrite: If False, raises FileExistsError when file exists.

    Returns:
        Path to the written file.

    Raises:
        FileExistsError: If config exists and overwrite is False.
    """
    config_dir = project_root / ".raise"
    config_path = config_dir / "confluence.yaml"

    if config_path.exists() and not overwrite:
        msg = f"{config_path} already exists. Use overwrite=True to replace."
        raise FileExistsError(msg)

    config_dir.mkdir(parents=True, exist_ok=True)

    with open(config_path, "w") as f:
        f.write(_CONFIG_HEADER)
        yaml.dump(config_dict, f, default_flow_style=False, sort_keys=False)

    return config_path
