"""Backlog sync: query remote adapter, format markdown, write atomically.

Generates ``governance/backlog.md`` from a remote PM adapter (e.g., Jira).
The filesystem adapter is detected and rejected (it IS the source of truth).

Architecture: S347.6 (E347 Backlog Automation)
"""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

from raise_cli.adapters.models import IssueSummary

if TYPE_CHECKING:
    from raise_cli.adapters.protocols import ProjectManagementAdapter


class SyncResult(BaseModel):
    """Result of a backlog sync operation."""

    adapter_name: str = Field(..., description="Name of source adapter")
    epic_count: int = Field(..., description="Number of epics synced")
    timestamp: str = Field(..., description="ISO 8601 sync timestamp")
    output_path: str = Field(..., description="Path to generated file")


def sync_backlog(
    adapter: ProjectManagementAdapter,
    adapter_name: str,
    project_filter: str | None,
    output_path: Path,
) -> SyncResult:
    """Query adapter, format markdown, write atomically.

    Raises:
        ValueError: If adapter is a FilesystemPMAdapter (self-sync).
        RuntimeError: If adapter query fails (file left untouched).
    """
    # Guard: filesystem adapter is source of truth
    from raise_cli.adapters.filesystem import FilesystemPMAdapter

    if isinstance(adapter, FilesystemPMAdapter):
        raise ValueError("Filesystem adapter is source of truth — nothing to sync.")

    # Build query
    query = "issuetype = Epic ORDER BY key ASC"
    if project_filter:
        query = f'project = "{project_filter}" AND issuetype = Epic ORDER BY key ASC'

    # Fetch from adapter — let exceptions propagate (file untouched)
    try:
        results = adapter.search(query, limit=200)
    except Exception as exc:
        raise RuntimeError(f"Adapter '{adapter_name}' failed: {exc}") from exc

    # Format and write
    timestamp = datetime.now(UTC).isoformat()
    content = _format_markdown(results, adapter_name, timestamp)
    _atomic_write(output_path, content)

    return SyncResult(
        adapter_name=adapter_name,
        epic_count=len(results),
        timestamp=timestamp,
        output_path=str(output_path),
    )


def _escape_pipe(value: str) -> str:
    """Escape pipe characters in markdown table cell values."""
    return value.replace("|", "\\|")


def _format_markdown(
    epics: list[IssueSummary], adapter_name: str, timestamp: str
) -> str:
    """Generate markdown table from IssueSummary list."""
    lines: list[str] = [
        f"<!-- Generated by `rai backlog sync` at {timestamp} from adapter: {adapter_name} -->",
        "<!-- Do not edit manually. Re-run `rai backlog sync` to refresh. -->",
        "",
        "# Backlog",
        "",
        "## Epics Overview",
        "",
        "| Key | Epic | Status | Type |",
        "|-----|------|--------|------|",
    ]
    for epic in epics:
        summary = _escape_pipe(epic.summary)
        status = _escape_pipe(epic.status)
        issue_type = _escape_pipe(epic.issue_type)
        lines.append(f"| {epic.key} | {summary} | {status} | {issue_type} |")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def _atomic_write(path: Path, content: str) -> None:
    """Write content to path atomically via temp file + rename.

    Uses ``str(path) + ".tmp"`` to preserve the original suffix
    (e.g., ``backlog.md.tmp`` not ``backlog.tmp``).
    Uses :func:`os.replace` instead of :meth:`Path.rename` for
    cross-platform atomicity (``rename`` fails on Windows when target exists).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = Path(str(path) + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)
