"""Direnv .envrc generation for worktree-isolated dev stacks.

Generates a .envrc file that:
- Loads .env.dev via ``dotenv`` (direnv builtin)
- Activates the worktree's isolated venv (.venv.dev)
- Falls back to .venv when .venv.dev is absent
- Sets a deterministic RAI_JWT_SECRET per worktree slug
"""

from __future__ import annotations

import hashlib
from pathlib import Path

_ENVRC_TEMPLATE = """\
# Auto-generated by rai dev up -- do not edit manually.
# Regenerate: rai dev up (or rai dev envrc)

# Load worktree-isolated port assignments and DB URL
dotenv .env.dev

# Deterministic JWT secret for this worktree (dev-only, not for production)
export RAI_JWT_SECRET="{jwt_secret}"

# Activate worktree-isolated venv; fall back to default .venv
if [[ -d .venv.dev ]]; then
  source .venv.dev/bin/activate
elif [[ -d .venv ]]; then
  source .venv/bin/activate
fi
"""


def _derive_jwt_secret(slug: str) -> str:
    """Derive a deterministic dev-only JWT secret from the worktree slug.

    Uses SHA-256 to produce a 64-char hex string.  This is NOT
    cryptographically sensitive -- it is a dev convenience so that
    tokens minted in one session remain valid across restarts of
    the same worktree's stack.
    """
    return hashlib.sha256(
        f"raise-dev-jwt-{slug}".encode(), usedforsecurity=False
    ).hexdigest()


def generate_envrc(slug: str = "default") -> str:
    """Generate .envrc content for a worktree.

    Args:
        slug: Worktree slug (directory name), used to derive JWT secret.

    Returns:
        Shell-compatible .envrc content string.
    """
    jwt_secret = _derive_jwt_secret(slug)
    return _ENVRC_TEMPLATE.format(jwt_secret=jwt_secret)


def write_envrc(worktree_path: Path, content: str) -> Path:
    """Write .envrc to the worktree root.

    Returns the path to the written file.
    """
    target = worktree_path / ".envrc"
    target.write_text(content, encoding="utf-8")
    return target
