"""Cartridge infrastructure — pluggable domain knowledge with deterministic gates."""

from raise_core.cartridges.audit import AuditReport, DimensionResult, audit_cartridge
from raise_core.cartridges.chunker import Chunk, GenericChunker
from raise_core.cartridges.curate import (
    CurationDecision,
    CurationSession,
    CurationSessionState,
    CurationSummary,
    NodeDecision,
)
from raise_core.cartridges.embedding import (
    DEFAULT_MODEL,
    EMBEDDING_DIM,
    PASSAGE_PREFIX,
    QUERY_PREFIX,
    EmbeddingGenerator,
    EmbeddingProvider,
    write_embeddings,
)
from raise_core.cartridges.extract import (
    CartridgeExtractionResult,
    CartridgeExtractor,
    ExtractorConfig,
    ExtractorSpec,
    MarkdownExtractor,
    YAMLExtractor,
    extract_cartridge,
)
from raise_core.cartridges.hygiene import (
    DedupReport,
    DedupResult,
    EdgeTypeReport,
    HygieneReport,
    HygieneResult,
    NormalizeResult,
    apply_hygiene,
    dedup_nodes,
    normalize_edge_types,
)
from raise_core.cartridges.models import (
    AIDisclosure,
    CartridgeDependency,
    CartridgeManifest,
    CartridgeRequires,
    CartridgeTier,
    GateConfig,
    GateResult,
    PromptingConfig,
    RetrievalConfig,
    SchemaRef,
)
from raise_core.cartridges.reconcile import (
    BrokenRelationship,
    ReconciliationReport,
    reconcile_nodes,
)
from raise_core.cartridges.validate import ValidationResult, validate_cartridge

__all__ = [
    "Chunk",
    "CurationDecision",
    "CurationSession",
    "CurationSessionState",
    "CurationSummary",
    "GenericChunker",
    "NodeDecision",
    "BrokenRelationship",
    "DedupReport",
    "DedupResult",
    "EdgeTypeReport",
    "HygieneReport",
    "HygieneResult",
    "NormalizeResult",
    "ReconciliationReport",
    "apply_hygiene",
    "dedup_nodes",
    "normalize_edge_types",
    "reconcile_nodes",
    "AIDisclosure",
    "CartridgeDependency",
    "CartridgeManifest",
    "CartridgeRequires",
    "CartridgeTier",
    "GateConfig",
    "GateResult",
    "PromptingConfig",
    "RetrievalConfig",
    "SchemaRef",
    "CartridgeExtractionResult",
    "CartridgeExtractor",
    "DEFAULT_MODEL",
    "EMBEDDING_DIM",
    "PASSAGE_PREFIX",
    "QUERY_PREFIX",
    "EmbeddingGenerator",
    "EmbeddingProvider",
    "ExtractorConfig",
    "ExtractorSpec",
    "MarkdownExtractor",
    "AuditReport",
    "DimensionResult",
    "audit_cartridge",
    "ValidationResult",
    "YAMLExtractor",
    "extract_cartridge",
    "validate_cartridge",
    "write_embeddings",
]
