"""BobPlugin — generates RaiSE config files for IBM Bob.

Creates .bob/custom_modes.yaml (rai-developer mode) and .bobrules (governance
rules always loaded) via the AgentPlugin.post_init hook called by
`rai init --agent bob`.

Architecture: ADR-032 (Multi-agent skill distribution).
Research: work/research/ibm-bob-integration/bob-identity-and-config.md
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from raise_cli.config.agents import AgentConfig

# Public — imported by purge.py as single source of truth (PAT-5e3732a7).
# Bob terminal group is "execute", NOT "command" (research doc §2).
BOB_CUSTOM_MODES_RAI_MODE: dict[str, Any] = {
    "slug": "rai-developer",
    "name": "RaiSE Developer",
    "roleDefinition": (
        "You are Rai, the RaiSE AI governance agent. "
        "You follow TDD (red-green-refactor), commit after each task, "
        "and never skip governance gates. "
        "You use the rai-workspace MCP server for pipeline, backlog, and graph operations."
    ),
    "whenToUse": "When implementing stories, fixing bugs, or writing code in a RaiSE project",
    "customInstructions": (
        "- Always check pipeline status via MCP before starting work\n"
        "- Follow TDD: write failing test first, then implementation, then refactor\n"
        "- Commit after each completed task, not just at story end\n"
        "- Run gates before pushing: uv run rai gate check --all\n"
        "- Use rai-workspace MCP tools for pipeline, backlog, and graph operations\n"
        "- Use `uv run rai` for CLI commands"
    ),
    "groups": ["read", "edit", "execute", "mcp", "skill"],
}

BOB_BOBRULES_CONTENT = """\
# RaiSE Governance Rules
# Generated by rai init --agent bob. Re-run to update.

## Pipeline
- Never start work without checking pipeline status first (use rai-workspace MCP)
- Never skip a pipeline phase: design → plan → implement → review → close
- Never advance a pipeline without passing all gates

## Code Quality
- TDD always: write failing test first, then implementation, then refactor
- Type annotations on all Python code (pyright strict)
- Use Pydantic for all data structures
- Run gates before committing: `uv run rai gate check --all`

## Commits
- Commit after each completed task, not just at story end
- Never amend published commits

## CLI
- Always use `uv run rai` to execute CLI commands (no global install)
- Use MCP tools from rai-workspace when available; fall back to CLI
"""


class BobPlugin:
    """Generate RaiSE config files for IBM Bob.

    Pass-through for skill/instructions transforms — AGENTS.md and SKILL.md
    are native Bob formats that need no transformation.
    """

    def transform_instructions(self, content: str, _config: AgentConfig) -> str:
        """Return instructions unchanged — AGENTS.md is native Bob format."""
        return content

    def transform_skill(
        self, frontmatter: dict[str, Any], body: str, _config: AgentConfig
    ) -> tuple[dict[str, Any], str]:
        """Return skill unchanged — SKILL.md is native Bob format."""
        return dict(frontmatter), body

    def post_init(self, project_root: Path, _config: AgentConfig) -> list[str]:
        """Write .bob/custom_modes.yaml (merge) and .bobrules (overwrite).

        custom_modes.yaml uses merge semantics — existing user modes are
        preserved; rai-developer is appended only if absent (idempotent).

        .bobrules is rai-owned and always overwritten with canonical content.

        Args:
            project_root: Project root directory.
            _config: Bob agent configuration (unused — all paths are fixed).

        Returns:
            List of relative file paths created/updated.
        """
        bob_dir = project_root / ".bob"
        bob_dir.mkdir(parents=True, exist_ok=True)

        created: list[str] = []

        # --- .bob/custom_modes.yaml (merge) ---
        modes_path = bob_dir / "custom_modes.yaml"
        existing_modes: list[dict[str, Any]] = []
        if modes_path.is_file():
            try:
                data = yaml.safe_load(modes_path.read_text(encoding="utf-8"))
                if isinstance(data, dict) and isinstance(data.get("customModes"), list):
                    existing_modes = data["customModes"]
            except yaml.YAMLError:
                existing_modes = []

        already_present = any(m.get("slug") == "rai-developer" for m in existing_modes)
        if not already_present:
            existing_modes.append(dict(BOB_CUSTOM_MODES_RAI_MODE))

        modes_path.write_text(
            yaml.dump(
                {"customModes": existing_modes},
                default_flow_style=False,
                allow_unicode=True,
            ),
            encoding="utf-8",
        )
        created.append(str(modes_path.relative_to(project_root)))

        # --- .bobrules (rai-owned, always overwrite) ---
        bobrules_path = project_root / ".bobrules"
        bobrules_path.write_text(BOB_BOBRULES_CONTENT, encoding="utf-8")
        created.append(str(bobrules_path.relative_to(project_root)))

        # --- .bob/mcp.json (Bob reads MCP from .bob/, not root .mcp.json) ---
        from raise_cli.agents.mcp_template import MCP_JSON_CONTENT

        bob_mcp_path = bob_dir / "mcp.json"
        bob_mcp_path.write_text(
            json.dumps(MCP_JSON_CONTENT, indent=2) + "\n",
            encoding="utf-8",
        )
        created.append(str(bob_mcp_path.relative_to(project_root)))

        return created
