"""CLAUDE.md generation for project onboarding.

Generates a project-specific CLAUDE.md file with detected conventions,
project structure, and references to governance artifacts.
"""

from __future__ import annotations

from datetime import date

from raise_cli.onboarding.conventions import ConventionResult
from raise_cli.onboarding.detection import DetectionResult, ProjectType


class ClaudeMdGenerator:
    """Generates CLAUDE.md content from detection results.

    Creates a context-rich CLAUDE.md that helps Claude Code understand
    the project's conventions, structure, and governance.
    """

    def generate(
        self,
        project_name: str,
        detection: DetectionResult,
        conventions: ConventionResult | None = None,
    ) -> str:
        """Generate CLAUDE.md content.

        Args:
            project_name: Name of the project.
            detection: Project detection result (type, file count).
            conventions: Optional convention detection result.

        Returns:
            Markdown content for CLAUDE.md.
        """
        lines: list[str] = []

        # Header
        lines.append(f"# {project_name}")
        lines.append("")

        # Project context
        project_type = detection.project_type.value
        lines.append(f"> {project_type.capitalize()} project with RaiSE governance")
        lines.append("")

        if detection.project_type == ProjectType.GREENFIELD:
            return self._generate_greenfield(lines, project_name)

        return self._generate_brownfield(lines, project_name, detection, conventions)

    def _generate_greenfield(
        self,
        lines: list[str],
        project_name: str,
    ) -> str:
        """Generate CLAUDE.md for greenfield project."""
        lines.append("## Project Status")
        lines.append("")
        lines.append(
            "This is a new project. Conventions will be established as code is written."
        )
        lines.append("")
        lines.append("## Getting Started")
        lines.append("")
        lines.append("1. Define your initial architecture")
        lines.append("2. Write code following your preferred conventions")
        lines.append(
            "3. Run `raise init --detect` after establishing patterns to generate guardrails"
        )
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by RaiSE on {date.today().isoformat()}*")
        lines.append("")

        return "\n".join(lines)

    def _generate_brownfield(
        self,
        lines: list[str],
        project_name: str,
        detection: DetectionResult,
        conventions: ConventionResult | None,
    ) -> str:
        """Generate CLAUDE.md for brownfield project."""
        self._add_overview_section(lines, detection, conventions)
        if conventions:
            self._add_conventions_section(lines, conventions)
        if conventions and conventions.structure.source_dir:
            self._add_structure_section(lines, project_name, conventions)
        self._add_governance_section(lines)
        self._add_footer(lines)
        return "\n".join(lines)

    def _add_overview_section(
        self,
        lines: list[str],
        detection: DetectionResult,
        conventions: ConventionResult | None,
    ) -> None:
        """Add project overview section."""
        lines.append("## Project Overview")
        lines.append("")
        lines.append(f"- **Type:** Brownfield ({detection.code_file_count} code files)")
        if conventions:
            lines.append(
                f"- **Confidence:** {conventions.overall_confidence.value.upper()}"
            )
        lines.append("")

    def _add_conventions_section(
        self, lines: list[str], conventions: ConventionResult
    ) -> None:
        """Add code conventions section with style and naming."""
        lines.append("## Code Conventions")
        lines.append("")
        lines.append("Detected conventions for this project:")
        lines.append("")

        # Style
        style = conventions.style
        lines.append("### Style")
        lines.append("")
        if style.indentation.width:
            lines.append(f"- **Indentation:** {style.indentation.width} spaces")
        else:
            lines.append(f"- **Indentation:** {style.indentation.style}")
        lines.append(f"- **Quotes:** {style.quote_style.style}")
        lines.append(f"- **Line length:** {style.line_length.max_length} characters")
        lines.append("")

        # Naming
        naming = conventions.naming
        lines.append("### Naming")
        lines.append("")
        lines.append(f"- **Functions:** {naming.functions.pattern}")
        lines.append(f"- **Classes:** {naming.classes.pattern}")
        lines.append(f"- **Constants:** {naming.constants.pattern}")
        lines.append("")

    def _add_structure_section(
        self, lines: list[str], project_name: str, conventions: ConventionResult
    ) -> None:
        """Add project structure section."""
        lines.append("## Project Structure")
        lines.append("")
        structure = conventions.structure
        lines.append("```")
        lines.append(f"{project_name}/")
        if structure.source_dir:
            lines.append(f"├── {structure.source_dir}/    # Source code")
        if structure.test_dir:
            lines.append(f"├── {structure.test_dir}/    # Tests")
        if structure.common_patterns:
            for pattern in structure.common_patterns[:5]:
                lines.append(f"│   ├── {pattern}")
        lines.append("└── ...")
        lines.append("```")
        lines.append("")

    def _add_governance_section(self, lines: list[str]) -> None:
        """Add governance reference section."""
        lines.append("## Governance")
        lines.append("")
        lines.append("This project uses RaiSE governance. Key files:")
        lines.append("")
        lines.append(
            "- `governance/solution/guardrails.md` — Code standards and verification"
        )
        lines.append("- `.rai/manifest.yaml` — Project metadata")
        lines.append("")

    def _add_footer(self, lines: list[str]) -> None:
        """Add document footer."""
        lines.append("---")
        lines.append("")
        lines.append(
            f"*Generated by RaiSE on {date.today().isoformat()}. "
            "Review and customize as needed.*"
        )
        lines.append("")


def generate_claude_md(
    project_name: str,
    detection: DetectionResult,
    conventions: ConventionResult | None = None,
) -> str:
    """Convenience function to generate CLAUDE.md content.

    Args:
        project_name: Name of the project.
        detection: Project detection result.
        conventions: Optional convention detection result.

    Returns:
        Markdown content for CLAUDE.md.

    Example:
        >>> detection = detect_project_type(Path("/my/project"))
        >>> conventions = detect_conventions(Path("/my/project"))
        >>> content = generate_claude_md("my-api", detection, conventions)
        >>> Path("CLAUDE.md").write_text(content)
    """
    generator = ClaudeMdGenerator()
    return generator.generate(project_name, detection, conventions)
