"""Worktree provisioning: config generation and file propagation.

Epic: E8398 (FLEET-4) — Provisioning Tooling
Story: S8398.1 — Models y generadores
Story: S14897.1 — Minimal readiness evaluator (RAISE-14900)
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING, Literal, NamedTuple

import yaml
from pydantic import BaseModel

from raise_cli.compat import IS_FROZEN
from raise_cli.core.files import atomic_write
from raise_cli.mcp.workspace_config import (
    detect_mcp_pipeline_command,
    render_codex_config_toml,
    workspace_project_args,
)
from raise_cli.workspace.readiness import (
    WorkspaceReadinessFinding,
    WorkspaceReadinessPolicy,
    WorkspaceReadinessReport,
    evaluate_workspace_readiness,
)

if TYPE_CHECKING:
    from raise_cli.skills.sync import SkillSyncer

_log = logging.getLogger(__name__)

# MCP server keys generated and owned by RaiSE provisioning.  User-owned
# entries (any other key) are preserved across repair calls.  (AC3, RAISE-14906)
# Directories that must NEVER be symlinked from the repo root into a worktree:
# a shared `.venv` makes the editable `.pth` resolve `raise_cli` to a different
# worktree's src (C4 / RAISE-10438), so in-worktree gates see stale code. These
# are created locally per worktree instead. `.venv-mcp` already has its own
# isolated-creation path (RAISE-9462). (E10436 S1)
_LOCAL_VENV_DIRS: frozenset[str] = frozenset({".venv"})
_RUNTIME_CONFIG_PATHS: tuple[str, ...] = (
    ".mcp.json",
    ".codex/config.toml",
    ".hermes/config.yaml",
)

_LOCK_FILE_NAMES: frozenset[str] = frozenset({"uv.lock", "Pipfile.lock"})


class HermesServerEntry(BaseModel, frozen=True):
    """A single MCP server entry in .hermes/config.yaml."""

    command: str
    args: list[str] = []
    timeout: int = 120
    connect_timeout: int = 60


class HermesConfig(BaseModel):
    """Complete .hermes/config.yaml structure."""

    mcp_servers: dict[str, HermesServerEntry] = {}

    def to_yaml(self) -> str:
        """Serialize to YAML string."""
        data = {
            "mcp_servers": {
                name: {
                    "command": entry.command,
                    "args": entry.args,
                    "timeout": entry.timeout,
                    "connect_timeout": entry.connect_timeout,
                }
                for name, entry in self.mcp_servers.items()
            }
        }
        return "# Auto-generated by rai worktree register --provision\n" + yaml.dump(
            data, default_flow_style=False, sort_keys=False
        )


class ProvisionResult(BaseModel):
    """Result of a worktree provisioning operation."""

    hermes_config_written: bool = False
    mcp_json_written: bool = False
    mcp_venv_created: bool = False
    main_venv_created: bool = False
    files_propagated: int = 0
    skills_synced: int = 0
    warnings: list[str] = []
    introduced_drift: list[str] = []
    dry_run: bool = False
    readiness_report: WorkspaceReadinessReport | None = None
    is_ready: bool = False


class HermesConfigGenerator:
    """Generates .hermes/config.yaml for a worktree."""

    def __init__(self, worktree_path: Path) -> None:
        self._wt = worktree_path

    def _detect_venv_python(self) -> str:
        for venv_name in (".venv-mcp", ".venv"):
            venv = self._wt / venv_name
            if venv.is_symlink():
                resolved = venv.resolve()
                candidate = resolved / "bin" / "python3"
                if candidate.exists():
                    return str(candidate)
            elif venv.is_dir():
                candidate = venv / "bin" / "python3"
                if candidate.exists():
                    return str(candidate)
        return "python3"

    def generate(self) -> HermesConfig:
        """Generate HermesConfig for this worktree."""
        python_path = self._detect_venv_python()
        return HermesConfig(
            mcp_servers={
                "raise": HermesServerEntry(
                    command=python_path,
                    args=["-m", "raise_cli.pipeline.mcp_server"],
                    timeout=120,
                    connect_timeout=60,
                )
            }
        )


class McpServerEntry(BaseModel, frozen=True):
    """A single MCP server entry in .mcp.json."""

    command: str
    args: list[str] = []


class McpJsonConfig(BaseModel):
    """Complete .mcp.json structure (Claude Code MCP server discovery file)."""

    mcp_servers: dict[str, McpServerEntry] = {}

    def to_json(self) -> str:
        """Serialize to JSON string with the camelCase `mcpServers` key.

        Claude Code's `.mcp.json` schema uses camelCase (`mcpServers`), unlike
        Hermes's `.hermes/config.yaml` which uses snake_case (`mcp_servers`) —
        this is the one real schema difference between the two generators.
        """
        data = {
            "mcpServers": {
                name: {"command": entry.command, "args": entry.args}
                for name, entry in self.mcp_servers.items()
            }
        }
        return json.dumps(data, indent=2) + "\n"


def _has_python_project(path: Path) -> bool:
    """Return True when the directory looks like a Python project uv can sync.

    Checks for the presence of pyproject.toml or uv.toml — the two files that
    tell uv where project dependencies are declared. setup.py is intentionally
    excluded: uv does not support legacy setuptools projects without a pyproject.
    Non-Python projects (JS, Go, Rust, plain monorepos) have none of these files
    and must skip venv creation entirely (RAISE-15153).
    """
    return (path / "pyproject.toml").exists() or (path / "uv.toml").exists()


class McpJsonGenerator:
    """Generates .mcp.json for a worktree (RAISE-10767).

    Fixes the MCP editable-install clobbering bug: a worktree's `.mcp.json`
    previously resolved `rai-mcp-pipeline` via bare PATH lookup, which could
    silently pick up a different worktree's editable install. Resolving the
    absolute path to THIS worktree's isolated `.venv-mcp` binary closes that
    gap.
    """

    def __init__(self, worktree_path: Path) -> None:
        self._wt = worktree_path

    def generate(self) -> McpJsonConfig:
        """Generate McpJsonConfig for this worktree.

        Uses workspace_project_args from the builder module (S15457.3 AC1):
        no hand-composed --project literal; resolves to absolute path (AC2).
        """
        command = detect_mcp_pipeline_command(self._wt)
        return McpJsonConfig(
            mcp_servers={
                "rai-workspace": McpServerEntry(
                    command=command,
                    args=workspace_project_args(self._wt),
                )
            }
        )


def _build_skill_syncer(
    worktree_path: Path, *, owned_destinations_only: bool = False
) -> SkillSyncer:
    """Build a SkillSyncer rooted at ``worktree_path``.

    Explicit sync targets every configured projection. Readiness checks instead
    target only projections versioned by the repository, so consumer checkouts
    are not judged against raise-commons-only destinations.
    """
    from raise_cli.config.agents import BUILTIN_AGENTS
    from raise_cli.skills.sync import SkillSyncer

    skills_base = (
        worktree_path / "packages" / "raise-cli" / "src" / "raise_cli" / "skills_base"
    )
    agent_skill_dirs = [
        worktree_path / cfg.skills_dir
        for cfg in BUILTIN_AGENTS.values()
        if cfg.skills_dir and cfg.skills_dir != ".claude/skills"
    ]
    if owned_destinations_only:
        agent_skill_dirs = [
            destination
            for destination in agent_skill_dirs
            if _is_git_tracked(
                worktree_path, destination.relative_to(worktree_path).as_posix()
            )
        ]
        if not _is_git_tracked(
            worktree_path, skills_base.relative_to(worktree_path).as_posix()
        ):
            # Comparing the canonical source to itself cleanly omits the
            # raise-commons distribution destination for consumer repositories.
            skills_base = worktree_path / ".claude" / "skills"
    return SkillSyncer(
        source=worktree_path / ".claude" / "skills",
        skills_base=skills_base,
        agent_skill_dirs=agent_skill_dirs,
    )


# ---------------------------------------------------------------------------
# Git worktree readiness policy — S14897.1 / RAISE-14900
# ---------------------------------------------------------------------------


def _check_workspace_root(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: workspace root must exist and be a directory."""
    if not path.is_dir():
        return [
            WorkspaceReadinessFinding(
                code="workspace_root_missing",
                message=f"Workspace root does not exist or is not a directory: {path}",
                severity="required",
                path=path,
            )
        ]
    return []


def _codex_project_finding(
    workspace: Path,
    config_path: Path,
    server_name: str,
    args: object,
) -> WorkspaceReadinessFinding | None:
    """Validate the Codex server's ``--project`` workspace pointer."""
    project_value: str | None = None
    if isinstance(args, list):
        try:
            index = args.index("--project")
            value = args[index + 1] if index + 1 < len(args) else None
            project_value = str(value) if value is not None else None
        except ValueError:
            pass
    if project_value is None or not Path(project_value).is_absolute():
        return WorkspaceReadinessFinding(
            code="codex_config_relative_project",
            message=(
                f".codex/config.toml {server_name} has a missing or relative "
                f"--project value ({project_value!r}). Run: rai worktree provision"
            ),
            severity="advisory",
            path=config_path,
        )
    resolved_workspace = workspace.resolve()
    if Path(project_value).resolve() != resolved_workspace:
        return WorkspaceReadinessFinding(
            code="codex_config_project_outside_workspace",
            message=(
                f".codex/config.toml {server_name} points to {project_value!r}; "
                f"expected exact workspace root {resolved_workspace}"
            ),
            severity="required",
            path=config_path,
            evidence={"project": project_value},
        )
    return None


def _check_codex_config(path: Path) -> list[WorkspaceReadinessFinding]:
    """Check .codex/config.toml: existence, mcp_servers table, and project assertion.

    Required findings (severity=required):
      codex_config_missing           — file absent
      codex_config_missing_mcp_servers — file present but has no mcp_servers table

    Advisory finding (severity=advisory, AC9 — SHOULD from S15457.3):
      codex_config_relative_project  — --project is missing or relative (not absolute)
        Re-provisioning with ``rai worktree provision`` fixes this.
    """
    import tomllib

    config_path = path / ".codex" / "config.toml"
    if not config_path.exists():
        return [
            WorkspaceReadinessFinding(
                code="codex_config_missing",
                message=f".codex/config.toml not found at {config_path}",
                severity="required",
                path=config_path,
            )
        ]
    content = config_path.read_text(encoding="utf-8")
    if "mcp_servers" not in content:
        return [
            WorkspaceReadinessFinding(
                code="codex_config_missing_mcp_servers",
                message=f".codex/config.toml does not contain mcp_servers table: {config_path}",
                severity="required",
                path=config_path,
            )
        ]

    # AC9 (SHOULD): warn when --project is missing or relative.
    # After S15457.3, a correctly generated config always has an absolute
    # --project arg.  A relative "." produces a false identity assertion
    # after S15457.2/S15457.4 (worktree_mismatch / exit 2).
    findings: list[WorkspaceReadinessFinding] = []
    try:
        from raise_cli.mcp.workspace_config import WORKSPACE_SERVER_NAME

        data = tomllib.loads(content)
        mcp_servers = data.get("mcp_servers", {})
        if isinstance(mcp_servers, dict):
            server = mcp_servers.get(WORKSPACE_SERVER_NAME, {})
            if isinstance(server, dict):
                finding = _codex_project_finding(
                    path, config_path, WORKSPACE_SERVER_NAME, server.get("args", [])
                )
                if finding is not None:
                    findings.append(finding)
    except tomllib.TOMLDecodeError as exc:
        findings.append(
            WorkspaceReadinessFinding(
                code="codex_config_parse_error",
                message=f".codex/config.toml is not valid TOML: {exc}",
                severity="required",
                path=config_path,
            )
        )
    except (OSError, KeyError):
        pass

    return findings


def _check_mcp_json(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: .mcp.json must exist and be a parseable JSON object."""
    mcp_path = path / ".mcp.json"
    if not mcp_path.exists():
        return [
            WorkspaceReadinessFinding(
                code="mcp_json_missing",
                message=f".mcp.json not found at {mcp_path}",
                severity="required",
                path=mcp_path,
            )
        ]
    try:
        parsed = json.loads(mcp_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        return [
            WorkspaceReadinessFinding(
                code="mcp_json_invalid",
                message=f".mcp.json is not valid JSON: {exc}",
                severity="required",
                path=mcp_path,
                evidence={"error": str(exc)},
            )
        ]
    if not isinstance(parsed, dict):
        return [
            WorkspaceReadinessFinding(
                code="mcp_json_invalid",
                message=f".mcp.json must be a JSON object, got {type(parsed).__name__}",
                severity="required",
                path=mcp_path,
            )
        ]
    return []


def _check_hermes_config(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: .hermes/config.yaml must exist and be non-empty."""
    hermes_path = path / ".hermes" / "config.yaml"
    if not hermes_path.exists():
        return [
            WorkspaceReadinessFinding(
                code="hermes_config_missing",
                message=f".hermes/config.yaml not found at {hermes_path}",
                severity="required",
                path=hermes_path,
            )
        ]
    content = hermes_path.read_text(encoding="utf-8").strip()
    if not content:
        return [
            WorkspaceReadinessFinding(
                code="hermes_config_empty",
                message=f".hermes/config.yaml is empty: {hermes_path}",
                severity="required",
                path=hermes_path,
            )
        ]
    return []


def _check_venv_python(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: .venv/bin/python must exist as a file (not just a directory).

    Skipped for non-Python projects (no pyproject.toml / uv.toml) — those
    projects have no Python dependencies and do not need a local venv (RAISE-15153).
    """
    if not _has_python_project(path):
        return []
    venv_python = path / ".venv" / "bin" / "python"
    if not venv_python.is_file():
        return [
            WorkspaceReadinessFinding(
                code="runtime_python_missing",
                message=f".venv/bin/python not found as file at {venv_python}",
                severity="required",
                path=venv_python,
            )
        ]
    return []


def _check_venv_mcp_python(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: .venv-mcp/bin/python must exist as a file (not just a directory).

    Skipped for non-Python projects (no pyproject.toml / uv.toml) — the MCP
    server runs from the global rai installation resolved via PATH (RAISE-15153).
    """
    if not _has_python_project(path):
        return []
    venv_mcp_python = path / ".venv-mcp" / "bin" / "python"
    if not venv_mcp_python.is_file():
        return [
            WorkspaceReadinessFinding(
                code="runtime_python_missing",
                message=f".venv-mcp/bin/python not found as file at {venv_mcp_python}",
                severity="required",
                path=venv_mcp_python,
            )
        ]
    return []


def _check_skill_drift(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: repository-owned skill projections must not be drifted."""
    try:
        drift = _build_skill_syncer(path, owned_destinations_only=True).check()
    except Exception:  # noqa: BLE001 — fail-open: missing skill dirs are advisory
        return []
    if drift.is_clean:
        return []
    total = len(drift.drift_skills_base) + sum(
        len(v) for v in drift.drift_agents.values()
    )
    return [
        WorkspaceReadinessFinding(
            code="skills_drifted",
            message=f"{total} skill(s) out of sync — run 'rai skill sync'",
            severity="required",
            evidence={"drift_count": total},
        )
    ]


def _check_server_command(
    server_name: str, command: str, workspace: Path
) -> WorkspaceReadinessFinding | None:
    """Return a finding if command is bare or an absolute path outside workspace."""
    if "/" not in command and "\\" not in command:
        return WorkspaceReadinessFinding(
            code="runtime_command_bare",
            message=(
                f"Runtime command '{command}' is bare — "
                "use an absolute path inside the workspace venv"
            ),
            severity="required",
            evidence={"command": command, "server": server_name},
        )
    cmd_path = Path(command)
    if cmd_path.is_absolute():
        try:
            cmd_path.relative_to(workspace)
        except ValueError:
            return WorkspaceReadinessFinding(
                code="runtime_command_outside_workspace",
                message=f"Runtime command '{command}' is outside the workspace root {workspace}",
                severity="required",
                evidence={"command": command, "server": server_name},
            )
    return None


def _check_runtime_commands(path: Path) -> list[WorkspaceReadinessFinding]:
    """Required: runtime command entries in .mcp.json must not be bare or outside workspace.

    Bare commands (single words with no path separator) cannot be pinned to a
    specific worktree's venv and risk picking up a different worktree's binary
    via PATH (RAISE-10767).

    Absolute paths outside the workspace root will stop working if the
    workspace is moved or if the path resolves to a system tool.

    Skipped for non-Python projects (no pyproject.toml / uv.toml): the MCP
    server binary lives in the global rai installation which is by definition
    outside the workspace — "outside workspace" is the correct and expected
    state for those projects (RAISE-15153).

    Skipped when frozen (IS_FROZEN=True): the installer places rai-mcp-pipeline
    in the global PATH (e.g. ~/.local/bin) — outside the workspace by design,
    same rationale as the non-Python exemption above (RAISE-15816).
    """
    if not _has_python_project(path):
        return []
    if IS_FROZEN:
        return []
    mcp_path = path / ".mcp.json"
    if not mcp_path.exists():
        return []  # mcp_json_missing will be reported by _check_mcp_json

    try:
        parsed = json.loads(mcp_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []  # mcp_json_invalid will be reported by _check_mcp_json

    if not isinstance(parsed, dict):
        return []

    # Claude Code uses camelCase "mcpServers" key; also handle snake_case
    servers = parsed.get("mcpServers") or parsed.get("mcp_servers") or {}
    findings: list[WorkspaceReadinessFinding] = []
    for server_name, entry in servers.items():
        if not isinstance(entry, dict):
            continue
        command = entry.get("command", "")
        if not isinstance(command, str) or not command:
            continue
        finding = _check_server_command(server_name, command, path)
        if finding is not None:
            findings.append(finding)
    return findings


# ---------------------------------------------------------------------------
# Adapter config static validation — S14927.5 / RAISE-14932
# ---------------------------------------------------------------------------


class _SectionSpec(NamedTuple):
    """Conditional section check — only runs if section_key is present in yaml data."""

    section_key: str
    required_keys: tuple[str, ...]
    optional_keys: tuple[str, ...]


class _AdapterSpec(NamedTuple):
    """Schema specification for a known adapter config file."""

    required_keys: tuple[str, ...]
    optional_keys: tuple[str, ...]
    sections: tuple[_SectionSpec, ...] = ()


# Known adapter filenames → schema.  Extend this map to add new adapters.
# For backlog.yaml the required/optional checks are conditional on the
# presence of the "jira" section — encoded via _SectionSpec.
_ADAPTER_SCHEMAS: dict[str, _AdapterSpec] = {
    "jira.yaml": _AdapterSpec(
        required_keys=("default_instance",),
        optional_keys=("instances", "projects"),
    ),
    # confluence.yaml is legacy (canonical is docs.yaml); schema varies by
    # format version (flat url vs multi-instance). Omitted until a stable
    # schema can be derived from ConfluenceConfig/ConfluenceInstanceConfig.
    "backlog.yaml": _AdapterSpec(
        required_keys=(),
        optional_keys=(),
        sections=(
            _SectionSpec(
                section_key="jira",
                required_keys=("default_org",),
                optional_keys=("organizations",),
            ),
        ),
    ),
}


def _adapter_key_findings(
    data: dict[str, object],
    required_keys: tuple[str, ...],
    optional_keys: tuple[str, ...],
    filename: str,
    config_path: Path,
    key_prefix: str = "",
) -> list[WorkspaceReadinessFinding]:
    """Return findings for missing required/optional keys in `data`.

    key_prefix is prepended to key names in messages and evidence when checking
    conditional section keys (e.g. "jira." for backlog.yaml's jira section).
    """
    findings: list[WorkspaceReadinessFinding] = []
    for key in required_keys:
        if key not in data:
            full = f"{key_prefix}{key}"
            findings.append(
                WorkspaceReadinessFinding(
                    code="adapter_config_missing_required_key",
                    message=f"{filename}: required key '{full}' is missing",
                    severity="required",
                    path=config_path,
                    evidence={"adapter": filename, "key": full},
                )
            )
    for key in optional_keys:
        if key not in data:
            full = f"{key_prefix}{key}"
            findings.append(
                WorkspaceReadinessFinding(
                    code="adapter_config_missing_optional_key",
                    message=f"{filename}: optional key '{full}' is missing",
                    severity="advisory",
                    path=config_path,
                    evidence={"adapter": filename, "key": full},
                )
            )
    return findings


def _adapter_file_findings(
    filename: str, spec: _AdapterSpec, config_path: Path
) -> list[WorkspaceReadinessFinding]:
    """Return all findings for one adapter config file.

    Handles parse errors, top-level key checks, and conditional section checks.
    """
    try:
        raw: object = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    except (yaml.YAMLError, OSError) as exc:
        return [
            WorkspaceReadinessFinding(
                code="adapter_config_parse_error",
                message=f"{filename} is not valid YAML: {exc}",
                severity="required",
                path=config_path,
                evidence={"error": str(exc)},
            )
        ]

    # yaml.safe_load returns None for an empty or comment-only file —
    # treat that as an empty document (no keys to validate).
    if raw is None:
        raw = {}

    if not isinstance(raw, dict):
        return [
            WorkspaceReadinessFinding(
                code="adapter_config_parse_error",
                message=f"{filename} must be a YAML mapping, got {type(raw).__name__}",
                severity="required",
                path=config_path,
            )
        ]

    data: dict[str, object] = raw
    findings = _adapter_key_findings(
        data, spec.required_keys, spec.optional_keys, filename, config_path
    )
    for section_spec in spec.sections:
        section = data.get(section_spec.section_key)
        if section is None or not isinstance(section, dict):
            continue  # section absent — not a finding
        findings.extend(
            _adapter_key_findings(
                section,
                section_spec.required_keys,
                section_spec.optional_keys,
                filename,
                config_path,
                key_prefix=f"{section_spec.section_key}.",
            )
        )
    return findings


def _check_adapter_config(path: Path) -> list[WorkspaceReadinessFinding]:
    """Advisory/required: validate adapter config files found in .raise/.

    Scans path/.raise/ for known adapter yaml files (jira.yaml, confluence.yaml,
    backlog.yaml).  For each found file:
      - YAML parse error        → severity="required", code="adapter_config_parse_error"
      - Missing required key    → severity="required", code="adapter_config_missing_required_key"
      - Missing optional key    → severity="advisory", code="adapter_config_missing_optional_key"

    Absence of an adapter file is not a finding — the adapter may not be
    configured for this project.  No network calls; filesystem-only.
    """
    raise_dir = path / ".raise"
    if not raise_dir.is_dir():
        return []
    findings: list[WorkspaceReadinessFinding] = []
    for filename, spec in _ADAPTER_SCHEMAS.items():
        config_path = raise_dir / filename
        if config_path.exists():
            findings.extend(_adapter_file_findings(filename, spec, config_path))
    return findings


def _check_tracked_runtime_configs(
    path: Path,
) -> list[WorkspaceReadinessFinding]:
    """Require checkout-specific runtime configs to be untracked local state."""
    findings: list[WorkspaceReadinessFinding] = []
    for relative_path in _RUNTIME_CONFIG_PATHS:
        if _is_git_tracked(path, relative_path):
            config_path = path / relative_path
            findings.append(
                WorkspaceReadinessFinding(
                    code="tracked_runtime_config",
                    message=(
                        f"{relative_path} is tracked branch content and was preserved. "
                        "Migrate it with a governed untrack-and-ignore commit before "
                        "re-provisioning."
                    ),
                    severity="required",
                    path=config_path,
                    evidence={"path": relative_path},
                )
            )
    return findings


def git_worktree_readiness_policy() -> WorkspaceReadinessPolicy:
    """Return the standard readiness policy for a git worktree provisioned by RaiSE.

    Checks (all required unless noted):
    - workspace root exists and is a directory
    - .codex/config.toml exists and contains mcp_servers shape
    - .mcp.json exists and is a valid JSON object
    - .hermes/config.yaml exists and is non-empty
    - .venv/bin/python exists as a file (not just a directory)
    - .venv-mcp/bin/python exists as a file
    - generated skills are not drifted
    - runtime command entries are not bare or outside the workspace
    - adapter config files in .raise/ have required keys (advisory: optional keys)

    Returns:
        A WorkspaceReadinessPolicy with all standard git worktree checks.
    """
    return WorkspaceReadinessPolicy(
        policy_id="git-worktree-v1",
        checks=[
            _check_workspace_root,
            _check_codex_config,
            _check_mcp_json,
            _check_hermes_config,
            _check_venv_python,
            _check_venv_mcp_python,
            _check_skill_drift,
            _check_runtime_commands,
            _check_tracked_runtime_configs,
            _check_adapter_config,
        ],
    )


def validate_provision(worktree_path: Path) -> list[str]:
    """Validate that critical files exist after provisioning.

    Backwards-compatible V1 API. Delegates to the structured readiness evaluator
    and returns required finding messages as plain strings for existing callers.

    For structured access, use:
        evaluate_workspace_readiness(worktree_path, git_worktree_readiness_policy())
    """
    report = evaluate_workspace_readiness(
        worktree_path, git_worktree_readiness_policy()
    )
    return [f.message for f in report.required_findings]


def _is_git_tracked(repo_root: Path, entry: str) -> bool:
    """Return True if `entry` (file or directory) has any git-tracked paths.

    Versioned entries already arrive correctly in a worktree via
    `git worktree add <branch>` — they match the worktree's OWN branch, not
    whatever `repo_root` happens to be parked on. Propagating them from
    `repo_root` (which may be a stale main checkout) would silently
    overwrite/symlink the worktree's own branch content (RAISE-13321).

    Returns False (not tracked) if `repo_root` is not a git repository —
    this keeps propagation working against plain non-repo fixture directories.
    """
    if not (repo_root / ".git").exists():
        return False
    try:
        result = subprocess.run(
            ["git", "ls-files", "--", entry],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0 and bool(result.stdout.strip())


def _git_porcelain_entries(repo_root: Path) -> dict[str, str]:
    """Return Git-visible worktree entries keyed by path."""
    if not (repo_root / ".git").exists():
        return {}
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain=v1", "--untracked-files=all"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return {}
    if result.returncode != 0:
        return {}
    return {line[3:]: line for line in result.stdout.splitlines() if len(line) >= 4}


def propagate_worktreeinclude(src_root: Path, dst_path: Path) -> tuple[int, list[str]]:
    """Propagate files listed in .worktreeinclude from src_root into dst_path.

    Files are copied; directories are symlinked. Missing entries produce
    warnings but do not fail. Idempotent: existing symlinks are skipped.
    Git-tracked (versioned) entries are always skipped — they belong to the
    destination worktree's own branch checkout, never to src_root (RAISE-13321).

    Returns (files_propagated, warnings).
    """
    wti = src_root / ".worktreeinclude"
    if not wti.exists():
        return 0, [f".worktreeinclude not found in {src_root}"]

    count = 0
    warnings: list[str] = []

    for raw in wti.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        entry = line.rstrip("/")
        if entry in _LOCAL_VENV_DIRS:
            # Never symlink a shared venv — it is created locally per worktree (C4).
            _log.debug(
                "Skipping %s in propagation — created locally per worktree", entry
            )
            continue
        if entry in _RUNTIME_CONFIG_PATHS:
            warnings.append(
                f"{entry} is a worktree-local runtime config and was not propagated"
            )
            continue
        if _is_git_tracked(src_root, entry):
            # Versioned — already arrives correctly from the worktree's own
            # branch checkout. Propagating from src_root would source it from
            # a possibly-stale main instead (RAISE-13321).
            _log.debug(
                "Skipping %s in propagation — git-tracked, sourced from branch checkout",
                entry,
            )
            continue
        src = src_root / entry
        if not src.exists():
            warnings.append(
                f"{entry} listed in .worktreeinclude but not found in {src_root}"
            )
            continue

        dst = dst_path / entry
        if src.is_dir():
            if not dst.exists():
                dst.symlink_to(src.resolve())
                count += 1
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            count += 1

    return count, warnings


class WorktreeProvisioner:
    """Orchestrates worktree provisioning: propagate + generate + validate."""

    def __init__(self, worktree_path: Path, repo_root: Path) -> None:
        self._wt = worktree_path
        self._repo = repo_root

    def _propagate_worktreeinclude(self) -> tuple[int, list[str]]:
        """Propagate files from .worktreeinclude. Returns (count, warnings).

        Delegates to the module-level `propagate_worktreeinclude()` so this
        call path and the CLI's direct call path (cli/commands/worktree.py)
        share one implementation — a prior duplicated copy of this logic here
        silently drifted from the module-level fix for git-tracked entries
        (RAISE-13321).
        """
        return propagate_worktreeinclude(self._repo, self._wt)

    def _create_mcp_venv(self) -> tuple[bool, list[str]]:
        """Create isolated .venv-mcp for the MCP server via uv sync.

        Skipped for non-Python projects (no pyproject.toml / uv.toml) — the MCP
        server is resolved from the global rai installation in those cases (RAISE-15153).
        """
        if not _has_python_project(self._wt):
            return True, []

        mcp_venv = self._wt / ".venv-mcp"
        if mcp_venv.is_dir():
            return True, []

        env = {**os.environ, "UV_PROJECT_ENVIRONMENT": str(mcp_venv)}
        try:
            subprocess.run(
                ["uv", "sync", "--frozen"],
                cwd=str(self._wt),
                env=env,
                capture_output=True,
                check=True,
                timeout=120,
            )
        except (subprocess.CalledProcessError, FileNotFoundError, TimeoutError) as exc:
            return False, [f".venv-mcp creation failed: {exc}"]
        return True, []

    def _create_main_venv(self) -> tuple[bool, list[str]]:
        """Create a worktree-local .venv via uv sync (E10436 S1, fixes C4).

        A real local .venv makes the editable .pth resolve raise_cli to THIS
        worktree's src, so in-worktree gates run the worktree's code. A
        pre-existing real .venv is left untouched (idempotent); a stale shared
        .venv symlink is removed and replaced by a real local venv.

        Skipped for non-Python projects (no pyproject.toml / uv.toml) — those
        have no Python dependencies and do not need a local venv (RAISE-15153).
        """
        if not _has_python_project(self._wt):
            return True, []

        venv = self._wt / ".venv"
        if venv.is_symlink():
            # Stale shared-venv pointer (the C4 case) — drop it, then sync locally.
            venv.unlink()
        elif venv.is_dir():
            return True, []

        env = {**os.environ, "UV_PROJECT_ENVIRONMENT": str(venv)}
        try:
            subprocess.run(
                ["uv", "sync"],
                cwd=str(self._wt),
                env=env,
                capture_output=True,
                check=True,
                timeout=300,
            )
        except (subprocess.CalledProcessError, FileNotFoundError, TimeoutError) as exc:
            return False, [f".venv creation failed: {exc}"]
        return True, []

    def _write_hermes_config(self) -> bool:
        """Write .hermes/config.yaml with structured upsert (preserves user entries)."""
        if _is_git_tracked(self._wt, ".hermes/config.yaml"):
            return False
        content = _render_hermes_config_content(self._wt)
        config_path = self._wt / ".hermes" / "config.yaml"
        return _write_config_if_changed(config_path, content)

    def _write_mcp_json(self) -> bool:
        """Write .mcp.json with structured upsert (preserves user entries)."""
        if _is_git_tracked(self._wt, ".mcp.json"):
            return False
        content = _render_mcp_json_content(self._wt)
        return _write_config_if_changed(self._wt / ".mcp.json", content)

    def _write_codex_config(self) -> bool:
        """Write .codex/config.toml with rai-workspace MCP server entry.

        Uses render_codex_config_toml from the builder module (S15457.3 AC1):
        - No hand-composed literals; output matches codex_plugin.post_init (AC4).
        - Absolute --project path resolves worktree_mismatch errors (AC2).
        - enabled_tools and env.RAISE_PROJECT_ROOT are never omitted (AC4/AC5).
        """
        if _is_git_tracked(self._wt, ".codex/config.toml"):
            return False
        content = _render_codex_config_content(self._wt)
        return _write_config_if_changed(self._wt / ".codex" / "config.toml", content)

    def _sync_skills(self) -> int:
        """Sync .claude/skills/ → skills_base/ + agent mirror dirs (RAISE-11153).

        Closes the gap where a freshly provisioned worktree fails the
        check-skills-sync pre-commit hook on first commit.
        """
        result = _build_skill_syncer(self._wt).sync()
        return len(result.synced_to_skills_base)

    def provision(self, *, dry_run: bool = False) -> ProvisionResult:
        """Run provisioning: propagate files, generate config, validate."""
        if dry_run:
            gen = HermesConfigGenerator(worktree_path=self._wt)
            config = gen.generate()
            _log.info(
                "[dry-run] Would write .hermes/config.yaml:\n%s", config.to_yaml()
            )
            return ProvisionResult(dry_run=True)

        before_drift = _git_porcelain_entries(self._wt)
        main_venv_created, main_warnings = self._create_main_venv()
        mcp_venv_created, mcp_warnings = self._create_mcp_venv()
        # .venv-mcp must exist before writing .mcp.json and .codex/config.toml
        # so the absolute rai-mcp-pipeline path can be resolved (RAISE-10767).
        mcp_json_written = self._write_mcp_json()
        codex_config_written = self._write_codex_config()
        _log.debug("codex_config_written=%s", codex_config_written)
        propagated, prop_warnings = self._propagate_worktreeinclude()
        hermes_written = self._write_hermes_config()
        # Skill projections are branch-owned source. Updating them remains an
        # explicit governed ``rai skill sync`` operation.
        skills_synced = 0

        report = evaluate_workspace_readiness(self._wt, git_worktree_readiness_policy())
        after_drift = _git_porcelain_entries(self._wt)
        introduced_drift = [
            entry
            for path, entry in after_drift.items()
            if path not in before_drift and path not in _LOCK_FILE_NAMES
        ]
        if introduced_drift:
            report = report.model_copy(
                update={
                    "findings": [
                        *report.findings,
                        WorkspaceReadinessFinding(
                            code="provision_introduced_git_drift",
                            message=(
                                "Provisioning introduced Git-visible drift: "
                                + ", ".join(introduced_drift)
                            ),
                            severity="required",
                            evidence={"entries": introduced_drift},
                        ),
                    ]
                }
            )
        readiness_warnings = [f.message for f in report.required_findings]

        return ProvisionResult(
            hermes_config_written=hermes_written,
            mcp_json_written=mcp_json_written,
            mcp_venv_created=mcp_venv_created,
            main_venv_created=main_venv_created,
            files_propagated=propagated,
            skills_synced=skills_synced,
            warnings=main_warnings + mcp_warnings + prop_warnings + readiness_warnings,
            introduced_drift=introduced_drift,
            readiness_report=report,
            is_ready=report.is_ready,
        )


# ---------------------------------------------------------------------------
# Render/apply split — RAISE-16231 (S16227.3)
# ---------------------------------------------------------------------------

ApplyStatus = Literal["written", "unchanged", "git-tracked", "not-main-checkout"]


class ConfigApplyResult(BaseModel, frozen=True):
    """Structured result of ``apply_runtime_config``."""

    status: ApplyStatus
    was_tracked: bool = False


def _write_config_if_changed(path: Path, content: str) -> bool:
    """Write *content* to *path* only when different from current text.

    Creates parent directories if needed.  Returns True when the file was
    actually written; False when content was identical (mtime untouched).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError:
            existing = None
        if existing == content:
            return False
    atomic_write(path, content)
    return True


def _render_mcp_json_content(wt: Path) -> str:
    """Generate .mcp.json content with upsert merge (preserves user entries)."""
    gen = McpJsonGenerator(worktree_path=wt)
    config = gen.generate()

    mcp_json_path = wt / ".mcp.json"
    existing_data: dict[str, object] = {}
    if mcp_json_path.exists():
        try:
            parsed: object = json.loads(mcp_json_path.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                existing_data = parsed
            else:
                _log.warning(
                    ".mcp.json is not a JSON object — overwriting with fresh content"
                )
        except (json.JSONDecodeError, OSError) as exc:
            _log.warning(
                ".mcp.json is malformed (%s) — overwriting with fresh content", exc
            )

    mcp_servers_raw = existing_data.get("mcpServers", {})
    if not isinstance(mcp_servers_raw, dict):
        mcp_servers_raw = {}
    mcp_servers: dict[str, object] = dict(mcp_servers_raw)

    new_json_data: dict[str, object] = json.loads(config.to_json())
    new_servers = new_json_data.get("mcpServers", {})
    if isinstance(new_servers, dict):
        mcp_servers.update(new_servers)

    result_data: dict[str, object] = dict(existing_data)
    result_data["mcpServers"] = mcp_servers
    return json.dumps(result_data, indent=2) + "\n"


def _render_hermes_config_content(wt: Path) -> str:
    """Generate .hermes/config.yaml content with upsert merge (preserves user entries)."""
    gen = HermesConfigGenerator(worktree_path=wt)
    config = gen.generate()

    config_path = wt / ".hermes" / "config.yaml"
    existing_data: dict[str, object] = {}
    if config_path.exists():
        try:
            parsed_yaml = yaml.safe_load(config_path.read_text(encoding="utf-8"))
            if isinstance(parsed_yaml, dict):
                existing_data = parsed_yaml
            else:
                _log.warning(".hermes/config.yaml is not a YAML mapping — overwriting")
        except Exception as exc:  # noqa: BLE001
            _log.warning(".hermes/config.yaml is malformed (%s) — overwriting", exc)

    mcp_servers_raw = existing_data.get("mcp_servers", {})
    if not isinstance(mcp_servers_raw, dict):
        mcp_servers_raw = {}
    mcp_servers: dict[str, object] = dict(mcp_servers_raw)

    new_yaml_data = yaml.safe_load(config.to_yaml())
    if isinstance(new_yaml_data, dict):
        new_servers = new_yaml_data.get("mcp_servers", {})
        if isinstance(new_servers, dict):
            mcp_servers.update(new_servers)

    result_data: dict[str, object] = dict(existing_data)
    result_data["mcp_servers"] = mcp_servers
    return yaml.dump(result_data, default_flow_style=False, sort_keys=False)


def _render_codex_config_content(wt: Path) -> str:
    """Generate .codex/config.toml content."""
    mcp_command = detect_mcp_pipeline_command(wt)
    return render_codex_config_toml(command=mcp_command, project_root=wt)


_RenderFn = Callable[[Path], str]

_RENDER_DISPATCH: dict[str, _RenderFn] = {
    ".mcp.json": _render_mcp_json_content,
    ".codex/config.toml": _render_codex_config_content,
    ".hermes/config.yaml": _render_hermes_config_content,
}


def render_runtime_config(project: Path, rel: str) -> str:
    """Would-be content for *rel* in ``_RUNTIME_CONFIG_PATHS``.  Never writes.

    Args:
        project: Project root.
        rel: One of ``.mcp.json``, ``.codex/config.toml``, ``.hermes/config.yaml``.

    Raises:
        ValueError: If *rel* is not a known runtime config path.
    """
    renderer = _RENDER_DISPATCH.get(rel)
    if renderer is None:
        msg = f"unknown runtime config rel: {rel!r}"
        raise ValueError(msg)
    return renderer(project)


def apply_runtime_config(
    project: Path,
    rel: str,
    *,
    ignore_tracked: bool = False,
) -> ConfigApplyResult:
    """Guarded write for a runtime config file.

    Guards: main-checkout -> tracked -> render -> unchanged check -> write.

    Args:
        project: Project root.
        rel: One of the ``_RUNTIME_CONFIG_PATHS`` values.
        ignore_tracked: When True, write even if the file is git-tracked.

    Returns:
        Structured result with status and was_tracked flag.

    Raises:
        ValueError: If *rel* is not a known runtime config path.
    """
    if rel not in _RENDER_DISPATCH:
        msg = f"unknown runtime config rel: {rel!r}"
        raise ValueError(msg)

    # Guard 1: main checkout
    if not (project / ".git").is_dir():
        return ConfigApplyResult(status="not-main-checkout")

    # Guard 2: git-tracked
    tracked = _is_git_tracked(project, rel)
    if tracked and not ignore_tracked:
        return ConfigApplyResult(status="git-tracked", was_tracked=True)

    content = render_runtime_config(project, rel)
    config_path = project / rel
    wrote = _write_config_if_changed(config_path, content)

    if wrote:
        return ConfigApplyResult(status="written", was_tracked=tracked)
    return ConfigApplyResult(status="unchanged", was_tracked=tracked)


def ensure_mcp_json(project: Path) -> bool:
    """Write ``.mcp.json`` at *project* when it is a main checkout (RAISE-15848).

    A main checkout has ``.git`` as a directory, unlike a linked worktree where
    ``.git`` is a file pointer (``gitdir:`` prefix).  Uses the same
    ``McpJsonGenerator`` + upsert machinery as ``rai worktree register`` so
    the generated content is identical: absolute path to ``.venv-mcp/bin/
    rai-mcp-pipeline`` and ``--project <absolute-root>`` (RAISE-10767, AC2).

    Called from ``build_open_report`` (``rai session open`` / ``raise_session_open``)
    so that developers get a working ``.mcp.json`` the first time they open a
    session on the root checkout — no manual ``rai worktree register`` needed.

    Returns ``True`` when the file was written or updated; ``False`` when
    *project* is a linked worktree (skipped) or git-tracking guards blocked
    the write.
    """
    if not (project / ".git").is_dir():
        # Linked worktree: .git is a file (gitdir pointer).  Provisioning
        # for linked worktrees is handled by ``rai worktree register``.
        return False
    provisioner = WorktreeProvisioner(project, project)
    return provisioner._write_mcp_json()  # type: ignore[reportPrivateUsage]


def ensure_runtime_config(project: Path, rel: str) -> bool:
    """Write a runtime config (codex/hermes) at *project/rel* when main checkout.

    Symmetric with ``ensure_mcp_json``: dispatches to the existing private
    writers for ``.codex/config.toml`` and ``.hermes/config.yaml``.
    Cleaner never calls privates directly.

    Returns ``True`` when the file was written or updated; ``False`` when
    *project* is a linked worktree or guards blocked the write.
    """
    if not (project / ".git").is_dir():
        return False
    provisioner = WorktreeProvisioner(project, project)
    if rel == ".codex/config.toml":
        return provisioner._write_codex_config()  # type: ignore[reportPrivateUsage]
    if rel == ".hermes/config.yaml":
        return provisioner._write_hermes_config()  # type: ignore[reportPrivateUsage]
    return False
