#!/usr/bin/env python3
"""Migrate documentation from filesystem to Confluence.

Reads manifest YAML files (generated by S935.2/S935.3), reads source
markdown files, publishes them to Confluence via REST API, and registers
page ID mappings in confluence-pages.yaml.

Auth: same as build-dossier.py — reads from .env or .raise/adapters/confluence.yaml.

Usage:
    python dev/scripts/migrate-to-confluence.py --manifest work/epics/e935-confluence-content-migration/manifest-raise-commons.yaml
    python dev/scripts/migrate-to-confluence.py --manifest work/epics/e935-confluence-content-migration/manifest-raise-gtm.yaml --source-root ../raise-gtm
    python dev/scripts/migrate-to-confluence.py --manifest manifest.yaml --dry-run
    python dev/scripts/migrate-to-confluence.py --manifest manifest.yaml --limit 10  # first 10 only
"""

from __future__ import annotations

import argparse
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, NamedTuple

import requests
import yaml


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DEFAULT_CONFIG = ".raise/adapters/confluence.yaml"
PAGES_REGISTRY = ".raise/confluence-pages.yaml"
RATE_LIMIT_DELAY = 1.0  # seconds between API calls
MAX_RETRIES = 3
RETRY_BACKOFF = 2.0


class ConfluenceAuth(NamedTuple):
    url: str
    user: str
    token: str


class MigrationEntry(NamedTuple):
    source: str
    space: str
    section: str
    parent_id: str
    title: str
    labels: list[str]


class MigrationResult(NamedTuple):
    source: str
    title: str
    page_id: str
    space: str
    status: str  # "created", "skipped", "failed"
    error: str


# ---------------------------------------------------------------------------
# Auth (shared with build-dossier.py)
# ---------------------------------------------------------------------------


def load_auth(config_path: str | None = None) -> ConfluenceAuth:
    """Load Confluence auth from .env, yaml config, or env vars."""
    import os

    # Try .env file first
    env_paths = [".env", str(Path.home() / "Code" / "raise-commons" / ".env")]
    for env_path in env_paths:
        if Path(env_path).exists():
            env_vars = _parse_dotenv(env_path)
            url = env_vars.get("JIRA_URL", env_vars.get("CONFLUENCE_URL", ""))
            user = env_vars.get("CONFLUENCE_USERNAME", env_vars.get("CONFLUENCE_USER", ""))
            token = env_vars.get("CONFLUENCE_API_TOKEN", "")
            if url and user and token:
                return ConfluenceAuth(url=url.rstrip("/"), user=user, token=token)

    # Try yaml config
    paths_to_try = [
        config_path,
        DEFAULT_CONFIG,
        str(Path.home() / ".raise" / "adapters" / "confluence.yaml"),
    ]
    for p in paths_to_try:
        if p and Path(p).exists():
            with open(p) as f:
                cfg = yaml.safe_load(f)
            if cfg and "url" in cfg:
                return ConfluenceAuth(url=cfg["url"].rstrip("/"), user=cfg["user"], token=cfg["token"])

    # Fallback to env vars
    url = os.environ.get("JIRA_URL", os.environ.get("CONFLUENCE_URL", ""))
    user = os.environ.get("CONFLUENCE_USERNAME", os.environ.get("CONFLUENCE_USER", ""))
    token = os.environ.get("CONFLUENCE_API_TOKEN", "")
    if url and user and token:
        return ConfluenceAuth(url=url.rstrip("/"), user=user, token=token)

    print("ERROR: No Confluence auth found.", file=sys.stderr)
    sys.exit(1)


def _parse_dotenv(path: str) -> dict[str, str]:
    result: dict[str, str] = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                result[key.strip()] = value.strip().strip("'\"")
    return result


# ---------------------------------------------------------------------------
# Confluence API (create pages)
# ---------------------------------------------------------------------------


_space_id_cache: dict[str, str] = {}


def get_space_id(auth: ConfluenceAuth, space_key: str) -> str:
    if space_key not in _space_id_cache:
        resp = requests.get(
            f"{auth.url}/wiki/api/v2/spaces",
            params={"keys": space_key, "limit": 1},
            auth=(auth.user, auth.token),
            headers={"Accept": "application/json"},
            timeout=30,
        )
        resp.raise_for_status()
        results = resp.json().get("results", [])
        if not results:
            print(f"ERROR: Space '{space_key}' not found", file=sys.stderr)
            sys.exit(1)
        _space_id_cache[space_key] = results[0]["id"]
    return _space_id_cache[space_key]


def find_page_by_title(auth: ConfluenceAuth, title: str, space_key: str) -> str | None:
    """Check if a page with this title already exists. Returns page ID or None."""
    space_id = get_space_id(auth, space_key)
    resp = requests.get(
        f"{auth.url}/wiki/api/v2/pages",
        params={"title": title, "space-id": space_id, "limit": 1},
        auth=(auth.user, auth.token),
        headers={"Accept": "application/json"},
        timeout=30,
    )
    resp.raise_for_status()
    results = resp.json().get("results", [])
    return results[0]["id"] if results else None


def create_page(
    auth: ConfluenceAuth,
    space_key: str,
    title: str,
    body_markdown: str,
    parent_id: str | None = None,
) -> str:
    """Create a Confluence page with markdown content. Returns page ID."""
    space_id = get_space_id(auth, space_key)
    payload: dict[str, Any] = {
        "spaceId": space_id,
        "status": "current",
        "title": title,
        "body": {
            "representation": "wiki",
            "value": body_markdown,
        },
    }
    if parent_id:
        payload["parentId"] = parent_id

    for attempt in range(MAX_RETRIES):
        try:
            resp = requests.post(
                f"{auth.url}/wiki/api/v2/pages",
                json=payload,
                auth=(auth.user, auth.token),
                headers={"Accept": "application/json", "Content-Type": "application/json"},
                timeout=60,
            )
            if resp.status_code == 429:
                wait = RETRY_BACKOFF * (attempt + 1)
                print(f"  Rate limited, waiting {wait}s...")
                time.sleep(wait)
                continue
            resp.raise_for_status()
            return resp.json()["id"]
        except requests.exceptions.RequestException as e:
            if attempt < MAX_RETRIES - 1:
                wait = RETRY_BACKOFF * (attempt + 1)
                print(f"  Retry {attempt + 1}/{MAX_RETRIES} after error: {e}")
                time.sleep(wait)
            else:
                raise
    msg = "Max retries exceeded"
    raise RuntimeError(msg)


def add_labels(auth: ConfluenceAuth, page_id: str, labels: list[str]) -> None:
    """Add labels to a page."""
    if not labels:
        return
    body = [{"prefix": "global", "name": label} for label in labels]
    resp = requests.post(
        f"{auth.url}/wiki/rest/api/content/{page_id}/label",
        json=body,
        auth=(auth.user, auth.token),
        headers={"Accept": "application/json", "Content-Type": "application/json"},
        timeout=30,
    )
    resp.raise_for_status()


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------


def load_manifest(manifest_path: str) -> list[MigrationEntry]:
    with open(manifest_path) as f:
        data = yaml.safe_load(f)

    entries: list[MigrationEntry] = []
    for item in data.get("entries", []):
        entries.append(
            MigrationEntry(
                source=item["source"],
                space=item["space"],
                section=item.get("section", ""),
                parent_id=item.get("parent_id", ""),
                title=item["title"],
                labels=item.get("labels", []),
            )
        )
    return entries


# ---------------------------------------------------------------------------
# Registry (confluence-pages.yaml)
# ---------------------------------------------------------------------------


def load_registry(registry_path: str) -> dict[str, str]:
    """Load existing source→page_id mappings."""
    p = Path(registry_path)
    if not p.exists() or p.stat().st_size == 0:
        return {}
    with open(p) as f:
        data = yaml.safe_load(f)
    return data if isinstance(data, dict) else {}


def save_registry(registry_path: str, registry: dict[str, str]) -> None:
    with open(registry_path, "w") as f:
        yaml.dump(registry, f, default_flow_style=False, sort_keys=True, allow_unicode=True)


# ---------------------------------------------------------------------------
# Migration engine
# ---------------------------------------------------------------------------


def migrate(
    auth: ConfluenceAuth,
    entries: list[MigrationEntry],
    source_root: Path,
    registry: dict[str, str],
    dry_run: bool = False,
    limit: int | None = None,
) -> list[MigrationResult]:
    results: list[MigrationResult] = []
    total = len(entries) if limit is None else min(limit, len(entries))

    for i, entry in enumerate(entries[:total]):
        source_path = source_root / entry.source
        prefix = f"[{i + 1}/{total}]"

        # Skip if already migrated
        if entry.source in registry:
            print(f"{prefix} SKIP (already migrated): {entry.title}")
            results.append(MigrationResult(entry.source, entry.title, registry[entry.source], entry.space, "skipped", ""))
            continue

        # Check source file exists
        if not source_path.exists():
            print(f"{prefix} SKIP (file not found): {source_path}")
            results.append(MigrationResult(entry.source, entry.title, "", entry.space, "failed", "file not found"))
            continue

        # Read content
        content = source_path.read_text(encoding="utf-8")

        if dry_run:
            print(f"{prefix} DRY-RUN: {entry.title} → {entry.space}/{entry.section}")
            results.append(MigrationResult(entry.source, entry.title, "dry-run", entry.space, "created", ""))
            continue

        # Check if page already exists in Confluence
        existing_id = find_page_by_title(auth, entry.title, entry.space)
        if existing_id:
            print(f"{prefix} SKIP (page exists): {entry.title} (id={existing_id})")
            registry[entry.source] = existing_id
            results.append(MigrationResult(entry.source, entry.title, existing_id, entry.space, "skipped", "already exists"))
            continue

        # Create page
        try:
            page_id = create_page(auth, entry.space, entry.title, content, entry.parent_id or None)
            add_labels(auth, page_id, entry.labels)
            registry[entry.source] = page_id
            print(f"{prefix} CREATED: {entry.title} (id={page_id})")
            results.append(MigrationResult(entry.source, entry.title, page_id, entry.space, "created", ""))
        except Exception as e:
            print(f"{prefix} FAILED: {entry.title} — {e}")
            results.append(MigrationResult(entry.source, entry.title, "", entry.space, "failed", str(e)))

        time.sleep(RATE_LIMIT_DELAY)

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def print_summary(results: list[MigrationResult]) -> None:
    created = sum(1 for r in results if r.status == "created")
    skipped = sum(1 for r in results if r.status == "skipped")
    failed = sum(1 for r in results if r.status == "failed")
    print(f"\n{'=' * 60}")
    print(f"Migration complete: {created} created, {skipped} skipped, {failed} failed")
    print(f"{'=' * 60}")
    if failed:
        print("\nFailed entries:")
        for r in results:
            if r.status == "failed":
                print(f"  - {r.source}: {r.error}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Migrate docs from filesystem to Confluence")
    parser.add_argument("--manifest", required=True, help="Path to manifest YAML file")
    parser.add_argument("--source-root", default=".", help="Root directory for source files (default: .)")
    parser.add_argument("--registry", default=PAGES_REGISTRY, help=f"Path to pages registry (default: {PAGES_REGISTRY})")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done without creating pages")
    parser.add_argument("--limit", type=int, help="Limit number of pages to process")
    parser.add_argument("--offset", type=int, default=0, help="Skip first N entries")
    args = parser.parse_args()

    # Load manifest
    print(f"Loading manifest: {args.manifest}")
    entries = load_manifest(args.manifest)
    print(f"Loaded {len(entries)} entries")

    if args.offset:
        entries = entries[args.offset:]
        print(f"Skipping first {args.offset}, processing from entry {args.offset + 1}")

    # Load auth
    if not args.dry_run:
        auth = load_auth()
        print(f"Authenticated to: {auth.url}")
    else:
        auth = ConfluenceAuth(url="", user="", token="")
        print("DRY RUN — no Confluence calls")

    # Load registry
    registry = load_registry(args.registry)
    print(f"Registry: {len(registry)} existing mappings")

    # Migrate
    source_root = Path(args.source_root)
    results = migrate(auth, entries, source_root, registry, dry_run=args.dry_run, limit=args.limit)

    # Save registry
    if not args.dry_run:
        save_registry(args.registry, registry)
        print(f"Registry saved: {len(registry)} total mappings")

    print_summary(results)


if __name__ == "__main__":
    main()
