"""WebSocket protocol frame types for the Rai daemon.

Three frame types over the wire:
  req   — client → daemon: method call with correlation id
  res   — daemon → client: response to a req (same id)
  event — daemon → client: server-push with monotonic seq for replay
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel


class ReqFrame(BaseModel):
    """Client → daemon: method invocation."""

    type: Literal["req"]
    id: str  # UUID — correlates with ResFrame
    method: str
    params: dict[str, Any] = {}


class ResFrame(BaseModel):
    """Daemon → client: response to a ReqFrame (same id)."""

    type: Literal["res"]
    id: str  # same UUID as the ReqFrame
    ok: bool
    payload: dict[str, Any] = {}
    error: str | None = None


class EventFrame(BaseModel):
    """Daemon → client: server-push event.

    seq is monotonically increasing per session.
    Clients that reconnect can request replay of missed events by seq.
    """

    type: Literal["event"]
    event: str
    payload: dict[str, Any] = {}
    seq: int  # monotonic per session
    state_version: int = 0


class AuthChallengePayload(BaseModel):
    """Payload for the auth_challenge event sent by daemon after WS upgrade."""

    nonce: str  # UUID generated by daemon, single-use


class AuthRequestPayload(BaseModel):
    """Payload for the auth req frame sent by client."""

    token: str  # Ed25519 signature of nonce with client's private key
