"""Claude Code MEMORY.md index regeneration.

Rebuilds MEMORY.md deterministically from frontmatter metadata in memory files.
Scans ``_global/`` (always), active mission dir (if set), ``_unassigned/``,
and root-level flat files (pre-migration backward compat).
"""

from __future__ import annotations

import logging
import re
import time
from pathlib import Path

_logger = logging.getLogger(__name__)

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)

_HEADER = """\
# Memory Index

> Auto-generated by `rai session start`. Do not edit manually.
"""

_TYPE_SECTIONS: dict[str, str] = {
    "user": "User",
    "feedback": "Feedback",
    "reference": "References",
    "project": "Global Context",
}

_IGNORED_DIRS = {"_backup", "__pycache__", ".git"}

# RAISE-13911 DD-5: "project active" = active-mission-scoped OR written within
# this many days. Named constant, adjustable without breaking the contract.
_PROJECT_ACTIVE_DAYS = 30


def _passes_tier1(entry: dict[str, str], *, is_active_scope: bool) -> bool:
    """Static Tier-1 policy (RAISE-13911 DD-5) — MEMORY.md carries Tier-1 only.

    Derived from ``metadata.type``:
        user      -> always Tier-1
        reference -> always Tier-2
        project   -> Tier-1 if active-mission-scoped (the file lives under
                     ``missions/{active_mission_id}/``), or ``critical: true``,
                     or ``mtime`` is within ``_PROJECT_ACTIVE_DAYS``, else
                     Tier-2
        feedback  -> Tier-1 only when frontmatter marks ``critical: true``

    Tier-2 is NOT automatically recoverable via ``hint_oracle.get_hints`` —
    that queries the knowledge graph, which only sees a demoted note after
    ``rai memory ingest --apply`` runs (nothing triggers it automatically,
    RAISE-16216). ``count_tier2_demoted`` + the session-start warning is
    the mitigation until/unless that ingest is wired into this flow.

    The ``critical`` flag is the one deliberate, additive departure from "no
    new frontmatter field v1": without SOME signal to separate feedback,
    tiering cannot demote the bulk of `_global/feedback_*` notes and AC-2
    (<17KB) is unreachable — the field is optional and defaults to Tier-2
    when absent, so every pre-existing note without it is conservatively
    demoted, never silently promoted.

    RAISE-16217: ``project`` reuses the same ``critical`` flag as an escape
    hatch from the mtime check — mtime measures when the file was written,
    not when the knowledge was last useful, and a dormant project has no
    active-mission-scope to fall back on.

    Any type outside this vocabulary defaults to Tier-2 (conservative).
    """
    mem_type = entry.get("type", "")
    if mem_type == "user":
        return True
    if mem_type == "reference":
        return False
    if mem_type == "feedback":
        return entry.get("critical", "").strip().lower() == "true"
    if mem_type == "project":
        if is_active_scope:
            return True
        if entry.get("critical", "").strip().lower() == "true":
            return True
        try:
            mtime = float(entry.get("mtime", "0"))
        except ValueError:
            return False
        age_days = (time.time() - mtime) / 86400
        return age_days < _PROJECT_ACTIVE_DAYS
    return False


def regenerate_memory_index(
    memory_dir: Path,
    active_mission_id: str | None = None,
) -> str:
    """Rebuild MEMORY.md from frontmatter of files in memory subdirs.

    Scans ``_global/`` (always) + ``missions/{active_mission_id}/`` (if set)
    + ``_unassigned/`` + root-level flat files.

    Returns the generated markdown string and writes it to
    ``memory_dir/MEMORY.md``.
    """
    sections: dict[str, list[str]] = {}

    _scan_dir(memory_dir, sections, recurse=False)

    global_dir = memory_dir / "_global"
    if global_dir.is_dir():
        _scan_dir(global_dir, sections)

    mission_entries = (
        _collect_entries(
            memory_dir / "missions" / active_mission_id, is_active_scope=True
        )
        if active_mission_id
        else []
    )
    unassigned_entries = _collect_entries(memory_dir / "_unassigned")

    lines = [_HEADER]
    _append_typed_sections(lines, sections)

    if active_mission_id and mission_entries:
        lines.append(f"## Mission: {active_mission_id}\n")
        lines.extend(mission_entries)
        lines.append("")

    if unassigned_entries:
        lines.append("## Unassigned\n")
        lines.extend(unassigned_entries)
        lines.append("")

    result = "\n".join(lines).rstrip() + "\n"
    memory_dir.mkdir(parents=True, exist_ok=True)
    (memory_dir / "MEMORY.md").write_text(result)
    return result


def count_tier2_demoted(
    memory_dir: Path,
    active_mission_id: str | None = None,
) -> int:
    """Count recognized-type entries `regenerate_memory_index` drops as Tier-2.

    Mirrors its scan scope exactly (root flat files, ``_global/``, active
    mission dir, ``_unassigned/``) so this never drifts from what actually
    left MEMORY.md — used to warn before the demotion is a silent loss
    (RAISE-16216: Tier-2 is only recoverable via hint_oracle if a cartridge
    ingest has run, which nothing does automatically).
    """

    def _demoted(
        directory: Path, *, is_active_scope: bool, recurse: bool = True
    ) -> int:
        return sum(
            1
            for e in _parse_memory_files(directory, recurse=recurse)
            if e.get("type", "") in _TYPE_SECTIONS
            and not _passes_tier1(e, is_active_scope=is_active_scope)
        )

    total = _demoted(memory_dir, is_active_scope=False, recurse=False)
    total += _demoted(memory_dir / "_global", is_active_scope=False)
    if active_mission_id:
        total += _demoted(
            memory_dir / "missions" / active_mission_id, is_active_scope=True
        )
    total += _demoted(memory_dir / "_unassigned", is_active_scope=False)
    return total


def _collect_entries(directory: Path, *, is_active_scope: bool = False) -> list[str]:
    """Collect formatted, Tier-1-only index entries from a memory subdirectory."""
    if not directory.is_dir():
        return []
    return [
        f"- [{e['name']}]({e['rel_path']}) — {e['description']}"
        for e in _parse_memory_files(directory)
        if _passes_tier1(e, is_active_scope=is_active_scope)
    ]


def _append_typed_sections(lines: list[str], sections: dict[str, list[str]]) -> None:
    """Append type-grouped sections to output lines."""
    for type_key, section_title in _TYPE_SECTIONS.items():
        entries = sections.get(type_key, [])
        if entries:
            lines.append(f"## {section_title}\n")
            lines.extend(entries)
            lines.append("")


def _scan_dir(
    scan_path: Path,
    sections: dict[str, list[str]],
    *,
    recurse: bool = True,
) -> None:
    """Parse memory files in a directory and group by type into sections.

    Applies the Tier-1 policy (``_passes_tier1``) — ``_global/`` and root-
    level flat files are never active-mission-scoped.
    """
    for entry in _parse_memory_files(scan_path, recurse=recurse):
        mem_type = entry.get("type", "")
        if mem_type not in _TYPE_SECTIONS:
            continue
        if not _passes_tier1(entry, is_active_scope=False):
            continue
        rel = entry["rel_path"]
        line = f"- [{entry['name']}]({rel}) — {entry['description']}"
        sections.setdefault(mem_type, []).append(line)


def _parse_memory_files(
    directory: Path, *, recurse: bool = True
) -> list[dict[str, str]]:
    """Parse all .md files in directory, extracting frontmatter fields."""
    results: list[dict[str, str]] = []
    if not directory.is_dir():
        return results

    pattern = "**/*.md" if recurse else "*.md"
    for md_file in sorted(directory.glob(pattern)):
        if md_file.name == "MEMORY.md":
            continue
        if any(part in _IGNORED_DIRS for part in md_file.parts):
            continue

        frontmatter = extract_frontmatter(md_file)
        if frontmatter is None:
            continue

        name = frontmatter.get("name", "").strip()
        description = frontmatter.get("description", "").strip()
        mem_type = frontmatter.get("type", "").strip()

        if not name or not description or not mem_type:
            _logger.debug("Skipping %s — missing required frontmatter fields", md_file)
            continue

        # Compute path relative to the memory root (parent of _global/, missions/, etc.)
        # Walk up to find the memory root
        memory_root = directory
        while memory_root.name in (
            "_global",
            "_unassigned",
            "missions",
        ) or (memory_root.parent.name == "missions"):
            memory_root = memory_root.parent

        rel_path = str(md_file.relative_to(memory_root))

        results.append(
            {
                "name": name,
                "description": description,
                "type": mem_type,
                "rel_path": rel_path,
                "critical": frontmatter.get("critical", "").strip(),
                "mtime": str(md_file.stat().st_mtime),
            }
        )

    return results


def frontmatter_body(path: Path) -> str:
    """Return the note text with the frontmatter block stripped.

    Reuses the same delimiter regex as ``extract_frontmatter()`` — the body
    is everything after the closing ``---``. Public counterpart used by
    ``MemoryFrontmatterExtractor`` (RAISE-13911) so the delimiter pattern
    has a single definition (AG2), not duplicated per caller.

    Returns the full text (stripped) unchanged if no frontmatter block is
    found, and ``""`` if the file cannot be read.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return text.strip()
    return text[match.end() :].strip()


def extract_frontmatter(path: Path) -> dict[str, str] | None:
    """Extract YAML-like frontmatter as simple key-value pairs."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    match = _FRONTMATTER_RE.match(text)
    if not match:
        return None

    result: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            result[key.strip()] = value.strip().strip('"').strip("'")

    return result
