"""Tactical BC breakdown and HTML report — Copper & Patina palette.

RAISE-16918: D4 — build_tactical_bc_breakdown() + render_tactical_html_report().

No external template engine (Jinja2 not a dependency). HTML uses inline f-strings.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_ALL_TYPES = [
    "entity",
    "value_object",
    "domain_service",
    "domain_event",
    "aggregate_root",
    "factory",
    "repository_interface",
]

_COPPER_PATINA_CSS = """\
  :root {
    --bg: #1a1412;
    --copper: #b87333;
    --patina: #5f9ea0;
    --snow: #f2ede8;
    --copper-dim: #8b5e27;
    --surface: #231c1a;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    background: var(--bg);
    color: var(--snow);
    font-family: 'Segoe UI', system-ui, sans-serif;
    padding: 2rem;
    line-height: 1.5;
  }
  h1 { color: var(--copper); margin-bottom: 0.5rem; font-size: 1.6rem; }
  .meta { color: var(--patina); font-size: 0.85rem; margin-bottom: 2rem; }
  .bc-section {
    background: var(--surface);
    border-left: 3px solid var(--patina);
    border-radius: 4px;
    margin-bottom: 1.5rem;
    overflow: hidden;
  }
  .bc-header {
    background: var(--surface);
    border-bottom: 1px solid var(--copper-dim);
    padding: 0.6rem 1rem;
    font-weight: 600;
    color: var(--patina);
    font-size: 1rem;
  }
  table { width: 100%; border-collapse: collapse; }
  th {
    background: var(--copper);
    color: var(--bg);
    padding: 0.4rem 0.8rem;
    text-align: left;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }
  td {
    padding: 0.4rem 0.8rem;
    border-bottom: 1px solid #2a2220;
    font-size: 0.875rem;
  }
  .count-high { color: var(--copper); font-weight: 600; }
  .count-low { color: var(--patina); }
  .count-zero { color: #555; }
  footer { margin-top: 2rem; color: var(--copper-dim); font-size: 0.75rem; }"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_tactical_bc_breakdown(
    annotations: dict[str, dict[str, Any]],
    bc_map: dict[str, str],
) -> dict[str, dict[str, int]]:
    """Build a BC → tactical_type → count breakdown from annotations.

    Args:
        annotations: Mapping of symbol_id → annotation dict.
            Each annotation dict must have a ``ddd_tactical_type`` key.
        bc_map: Mapping of symbol_id → bc_name.
            Symbols absent from *bc_map* are placed in ``"unassigned"``.

    Returns:
        ``{bc_name: {tactical_type: count}}`` — all BCs that appear in the
        annotations.  Zero-count types are omitted per BC (sparse representation).
    """
    breakdown: dict[str, dict[str, int]] = {}

    for symbol_id, ann in annotations.items():
        tactical_type = ann.get("ddd_tactical_type")
        if not tactical_type:
            continue
        bc = bc_map.get(symbol_id, "unassigned")
        if bc not in breakdown:
            breakdown[bc] = {}
        breakdown[bc][str(tactical_type)] = breakdown[bc].get(str(tactical_type), 0) + 1

    return breakdown


def render_tactical_html_report(
    breakdown: dict[str, dict[str, int]],
    total_classified: int,
    generated_at: str,
) -> str:
    """Render a standalone HTML report with Copper & Patina palette.

    Args:
        breakdown: Output of :func:`build_tactical_bc_breakdown`.
        total_classified: Total number of classified symbols (for summary header).
        generated_at: ISO timestamp string for the report footer.

    Returns:
        Complete HTML string — no external dependencies, inline CSS only.
    """
    bc_sections = _render_bc_sections(breakdown)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DDD Tactical Report</title>
  <style>
{_COPPER_PATINA_CSS}
  </style>
</head>
<body>
  <h1>DDD Tactical Type Report</h1>
  <p class="meta">
    Total classified: <strong>{total_classified}</strong> &nbsp;|&nbsp;
    Bounded contexts: <strong>{len(breakdown)}</strong> &nbsp;|&nbsp;
    Generated: {generated_at}
  </p>
  {bc_sections}
  <footer>Generated by rai ddd report &mdash; RAISE-16918</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _render_bc_sections(breakdown: dict[str, dict[str, int]]) -> str:
    sections: list[str] = []
    for bc_name in sorted(breakdown):
        counts = breakdown[bc_name]
        rows = _render_type_rows(counts)
        bc_total = sum(counts.values())
        sections.append(
            f"""<div class="bc-section">
    <div class="bc-header">{bc_name} &mdash; {bc_total} symbols</div>
    <table>
      <thead>
        <tr>
          <th>Tactical Type</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
  </div>"""
        )
    return "\n  ".join(sections)


def _render_type_rows(counts: dict[str, int]) -> str:
    rows: list[str] = []
    # Show all 7 types including zeros for completeness
    for t in _ALL_TYPES:
        c = counts.get(t, 0)
        if c >= 5:
            cls = "count-high"
        elif c > 0:
            cls = "count-low"
        else:
            cls = "count-zero"
        rows.append(f'<tr><td>{t}</td><td class="{cls}">{c}</td></tr>')
    return "\n        ".join(rows)
